#!/bin/bash

# Taken from https://stackoverflow.com/questions/8800578/how-to-colorize-diff-on-the-command-line/39865275#39865275

# Use diff-highlight to show word-level differences

diff -U3 --minimal "$@" |
  sed 's/^-/\x1b[1;31m-/;s/^+/\x1b[1;32m+/;s/^@/\x1b[1;34m@/;s/$/\x1b[0m/' |
  diff-highlight
