#!/bin/bash

if [ -z "$1" ]; then
  # No argument supplied
  if [ -f *.scf.out ]; then
    grep estimated *scf.out | awk '{print $(NF-1)}' > tmp_estimated
  elif [ -f *.relax.out ]; then
    grep estimated *relax.out | awk '{print $(NF-1)}' > tmp_estimated
  elif [ -f scf.out ]; then
    grep estimated scf.out | awk '{print $(NF-1)}' > tmp_estimated
  elif [ -f relax.out ]; then
    grep estimated relax.out | awk '{print $(NF-1)}' > tmp_estimated
  elif [ -f vcrelax.out ]; then
    grep estimated vcrelax.out | awk '{print $(NF-1)}' > tmp_estimated
  else
    echo "The *.scf.out or *.relax.out or scf.out or relax.out file does not exist"
    exit 0;
  fi
else
  grep estimated $1 | awk '{print $(NF-1)}' > tmp_estimated
fi

/usr/bin/gnuplot -e "set logscale y; set xlabel 'scf iteration'; set ylabel 'estimated scf accuracy (Ry)'; plot 'tmp_estimated' u 0:1 w lp ; pause -1"

if [ -f tmp_estimated ]; then
  rm tmp_estimated
fi


