#!/bin/bash
set -e
if [ -z "$1" ]; then
  lastmodfile=$(ls -t1 *out | head -n 1)
  file=$lastmodfile
else
  lastmodfile=$(ls -t1 $1 | head -n 1)
  file=$lastmodfile
  #file=$1
fi
watch -n 2 "tail -$(($(tput lines) - 2)) $file"

