#!/bin/bash
set -e
if [ -z "$1" ]; then
  # Tail last modified *.out file full screen
  watch -n 2 "ls -t1 *out | head -n 1 | xargs tail -$(($(tput lines) - 2))"
else
  # Tail $1 file full screen
  watch -n 2 "tail $1 -$(($(tput lines) - 2))"
fi
